obstacle_range: 3.0
raytrace_range: 8.0
footprint: [[ 0.3,  0.3], [-0.3,  0.3], [-0.3, -0.3], [ 0.3, -0.3]]
footprint_padding: 0.1
#robot_radius: ir_of_robot
inflation_radius: 0.55
transform_tolerance: 1
