controller_frequency: 10
controller_patience: 15

planner_frequency: 0.05
planner_patience: 10

oscillation_timeout: 0.0
oscillation_distance: 0.0

NavfnROS:
  allow_unknown: true
  default_tolerance: 0.5
  #visualize_potential: true

# TODO: reverse a little before rotate?
recovery_behaviors: [
  {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
  {name: rotate_recovery, type: rotate_recovery/RotateRecovery},
  {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
  ]

conservative_clear:
  reset_distance: 3.00
aggressive_clear:
  reset_distance: 0.01
rotate_recovery:
  sim_granularity: 0.017
  frequency: 10
