TrajectoryPlannerROS:

  acc_lim_x:  3.0
  acc_lim_y:  0.0
  acc_lim_theta: 1.0
  acc_lim_th: 1.0 # deprecated
  max_vel_x:  0.50
  min_vel_x:  0.05 # Reverse?
  max_rotational_vel: 1.0 # deprecated
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.15
  min_in_place_rotational_vel: 0.15 # deprecated
  escape_vel: -0.10
  #escape_reset_dist: 0.025
  #escape_reset_theta: 0.785398163395
  holonomic_robot: false

  xy_goal_tolerance:  0.15
  yaw_goal_tolerance: 0.15

  sim_time: 1.7
  sim_granularity: 0.1
  vx_samples: 8
  vy_samples: 8
  vtheta_samples: 20

  controller_frequency: 10

  path_distance_bias: 1.0
  goal_distance_bias: 0.6
  occdist_scale: 0.02

  heading_lookahead: 3.0
  dwa: true

  heading_scoring: true
  heading_scoring_timestep: 0.1

  oscillation_reset_dist: 0.00
  meter_scoring: true
  publish_cost_grid_pc: true

  y_vels: 0.0 # not working
